name: Notes Application CI Pipeline
# create a CI pipeline based on the assignment specification
# remember to commit often

on:
  push:
    branches:
      - main
      - feature/**
      - feature
  pull_request:
    branches:
      - main

defaults: 
  run:
    working-directory: src

jobs:
 # build:
  # runs-on: ubuntu-latest
  # steps:
   # - run: docker compose up -d
  #  - run: cd src
  #  - run: npm install

 ci-lint:
      
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - run: cd src
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"
    
    - run: npm clean-install

    - run: npm run lint
    
 ci-unit-test:
  needs: ci-lint
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3

  - name: Use Node.js 16.x
    uses: actions/setup-node@v3
    with:
      node-version: "16"
      cache: "npm"
      cache-dependency-path: '**/package-lock.json'
      
  - run: npm clean-install

  - run: npm run unit-tests
    
  - name: upload code coverage
    uses: actions/upload-artifact@v3
    with: 
      name: unit-test-code-coverage
      path: ./coverage/coverage-final.json
      
  - name: Validate Coverage
    uses: codecov/codecov-action@v2
    with:
      directory: ./coverage
      files: coverage-final.json
      fail_ci_if_error: true
      flags: unittests
      verbose: true
      dry_run: true

